services:
  db:
    image: postgres:latest
    container_name: postgres-queroler_clean_architecture
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_quero_ler_v2_clean_architecture}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${POSTGRES_DB:-db_quero_ler_v2_clean_architecture}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api-queroler_clean_architecture
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

